name: Flask Deployment
on:
   push:
        branches: [master]
jobs:
   Deploy:
     name: Deploy to VM
     runs-on: ubuntu-latest

     steps:
     - name: Deploy in VM
     env:
         PRIVATE_KEY: ${{ secrets.SSH_KEY }}
         HOST_NAME: ${{ secrets.HOST_NAME }}
         USER_NAME: ${{ secrets.USER_NAME }}

    run: |
       echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
       ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME}
       ls &&
       cd flask-hello-world/ &&
       ls &&
       git pull
